# permissions for end users to edit podchaosmonkeys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: podchaosoperator
    app.kubernetes.io/managed-by: kustomize
  name: podchaosmonkey-editor-role
rules:
- apiGroups:
  - chaos.jyisus.com
  resources:
  - podchaosmonkeys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - chaos.jyisus.com
  resources:
  - podchaosmonkeys/status
  verbs:
  - get
